default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: data_analyzing_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: data_analyzing_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  # database: data_analyzing_production
  # username: data_analyzing
  # password: <%= ENV["DATA_ANALYZING_DATABASE_PASSWORD"] %>
